on:
  schedule:
    # Runs every hour or use crontab.guru for custom cron
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-thing:
    name: Update this repo's README with latest MAL history
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: MyAnimeList readme workflow
        uses: gamersindo1223/genshinautogift@getcode
        with:
          gh_token: ${{ github.token }}