on:
  schedule:
    # Runs every day
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-codes:
    name: update
    runs-on: ubuntu-latest
    steps:
      - name: update active_codes.json
        run: |
          ls
          cd main
          ls
          
        shell: bash
